apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jssco7avx-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jssco7avx-nodejs 
  name: jssco7avx-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jssco7avx-nodejs 
